data:
  data_name: ca
  data_seed: 0
  batch_size: 128
  data_dir: "data"

label_pretrainer:
  hidden_dims: [8]
  n_hiddens: 1
  dropout_rate: 0.1
  use_batch_norm: true

optimizer:
  warmup: 1000
  rmsprop:
    lr: 0.0003
  adam:
    lr: 0.001

trainer:
  pretrain:
    n_epochs: 1000
    alpha: 1
    print_interval: 50
  finetune:
    n_epochs: 200
    print_interval: 10